In [1]:
import pandas as pd

In [2]:
usuarios = pd.read_excel('MATRIZ JANEIRO 2020 DIRCEU.xlsx')
bd = pd.read_excel('USUARIOS_DEZEMBRO.xlsx')

In [3]:
bd.set_index('matricula', inplace=True)
usuarios.set_index('matricula', inplace=True)

In [4]:
cidade = bd['cidade']

In [5]:
cidade = cidade.to_dict()

In [6]:
usuarios['cidade'] = usuarios.index.map(cidade)

In [7]:
usuarios

,nome,horario,Unnamed: 3,rua,numero,bairro,telefone,cidade
matricula,,,,,,,,
146841,ANANDA MARIA LIMA MORAIS DA SILVA,06:10:00,NaN,DUBAI,4921,REDONDA,988012007.0,TERESINA
125737,ANDREIA CARVALHO DE ARAUJO,06:10:00,NaN,QUADRA 211 CASA 13,13,ITARARE,94680402.0,TERESINA
154804,EDUARDO LOBATO CARVALHO,06:10:00,NaN,RUA PARA,893,MATINHA,988128102.0,TERESINA
166663,JACO FERREIRA CARVALHO LIMA,06:10:00,NaN,RUA AFONSO GIL,16,SANTA MARIA DA CODIPI,994657252.0,TERESINA
197861,MAX WENDEL PRADO ANTUNES DE AGUIAR,06:10:00,NaN,AV MIGUEL ROSA,5938,PIO XII,994708451.0,TERESINA
...,...,...,...,...,...,...,...,...
220832,ROSICLEIA ALVES DA SILVA,23:00:00,NaN,RUA PADRE TOMAZ REGO,312,CABRAL,988025105.0,NaN
222638,PEDRO MARCUS DE ASSIS FURTADO LIMA,00:00:00,NaN,AVENIDA MARECHAL CASTELO BRANCO,1299,ILHOTAS,995040224.0,NaN
238747,JOSIANE FRANCISCA DAS NEVES,23:30:00,NaN,RUA DOUTOR AREA LEAO,1108,NOSSA SENHORA DAS GRACAS,981489509.0,NaN
222657,PLACIDO AUGUSTO QUEIROZ DA SILVA,00:30:00,NaN,QUADRA 42,33,RENASCENCA,994795334.0,NaN
140412,RAFAELA CRISTINA RODRIGUES DA SILVA,23:10:00,NaN,RUA SANTO ANDRE,4523,NOVO HORIZONTE,94554189.0,NaN

In [8]:
usuarios.to_excel("cidade.xlsx")