In [1]:
import pandas as pd
import googlemaps

In [2]:
aracaju = pd.read_excel('aracaju_cidade.xlsx')

In [3]:
def localizacao(loc):
    try:
        gmaps = googlemaps.Client(key='AIzaSyBn33MytAEJqHoHRS6CtzbHQd7XmQRo2hU')
        geocode_result = gmaps.geocode(loc)
        lat = geocode_result[0]["geometry"]["location"]["lat"]
        lon = geocode_result[0]["geometry"]["location"]["lng"]
        return lat,lon
    except:
        return None

In [4]:
aracaju = aracaju.set_index('matricula')

In [5]:
aracaju['lat_lng'] = aracaju['endereço'].apply(localizacao)

In [6]:
aracaju

,nome,cep,horario,fretado,endereço,lat_lng
matricula,,,,,,
119244,ANA CLECIA DOS SANTOS,49100000,00:25:00,FRETADO - LINHA 03 B-Selo 22,"RUA MARIA DO CARMO SILVA, 0- ROSA ELZE, São Cr...","(-10.9282412, -37.1145824)"
141390,JHONATAN MOTA RODRIGUES,49100000,00:25:00,FRETADO - LINHA 03 B-Selo 22,"AV DULCINEIA ALMEIDA, 310- ROSA ELZE, São Cris...","(-10.9313922, -37.1105102)"
147828,BRENDA WILLIANE DE SOUZA SILVA,49072216,00:25:00,FRETADO - LINHA 03 B-Selo 22,"FRANCISCO CARDOSO DA SILVA, 33- DEZOITO DO FOR...","(-10.9015742, -37.063208)"
157479,MARIA JOSINA DE ARAUJO,49100000,00:25:00,FRETADO - LINHA 03 B-Selo 22,"RUA ALAN SILVA, 221- ROSA ELZE, São Cristóvão","(-10.9285382, -37.1120159)"
159163,DANIELE ALMEIDA CAMPOS,49080330,00:25:00,FRETADO - LINHA 03 B-Selo 22,"RUA JOSE PEREIRA DE OLIVEIRA, 137- AMERICA, Ar...","(-10.915614, -37.077257)"
...,...,...,...,...,...,...
249780,MANRICK DE LACERDA SANTOS,49090000,01:40:00,FRETADO -LINHA 06 A-Selo 28,"POCO DO MERO, 906- BUGIO, Aracaju","(-10.8881955, -37.0953152)"
249832,LOURIVAL OLIVEIRA MARQUES,49090346,01:40:00,FRETADO -LINHA 06 A-Selo 28,"ANA CELIA, 29- BUGIO, Aracaju","(-10.8876785, -37.0937588)"
250019,ELISSON SOCORRO FONTES OLIVEIRA,49065330,01:40:00,FRETADO -LINHA 06 A-Selo 28,"RUA EDUARDO CRUZ, 139- INDUSTRIAL, Aracaju","(-10.8975821, -37.05029)"
250024,LOYS LENE DE JESUS SANTOS,49160000,01:40:00,FRETADO -LINHA 06 A-Selo 28,"17, 104- TAICOCA, Nossa Senhora do Socorro","(-10.8559073, -37.1096016)"
250041,GLADSON FERREIRA DOS SANTOS,49000000,01:40:00,FRETADO -LINHA 06 A-Selo 28,"F DOIS, 431- JARDIM CENTENARIO,",None

In [9]:
bairros = pd.read_excel('BAIRROS_ARACAJU.xlsx')